version: "3"

# elastic_stack 单节点版本
# todo 未完成验证

services:
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms64m -Xmx128m
    volumes:
      - /docker/elastic_stack/elasticsearch/data:/usr/share/elasticsearch/data
      - /docker/elastic_stack/elasticsearch/download:/usr/share/elasticsearch/download

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - elasticsearch_url=elasricsearch:9200
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:7.9.3
    container_name: filebeat
    volumes:
      - /docker/elastic_stack/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /docker/elastic_stack/filebeat/logs:/var/log/filebeat/logs
    depends_on:
      - elasticsearch
      - kibana

  logstash:
    image: logstash:7.9.3
    container_name: logstash
    volumes:
      - /docker/elastic_stack/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /docker/elastic_stack/logstash/template.json:/etc/logstash/template.json
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch